### ISSUE TITLE
Specify Vue.js to load as an option

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/cypress-vue-unit-test#1]
Instead of hard coding the path to Vue.js in https://github.com/bahmutov/cypress-vue-unit-test/blob/master/src/index.js#L45 allow passing it as an option.

**Comment by patrikniebur** [comment]
It would be good to have this option de-deprecated. When I run a single test it's all ok and Vue is loaded, but when I run a test as a part of a serial test and one of them is using `cy.visit('myurl.local')` then it takes that root url and tries to load vue from there - resulting in 404 for vue and failing test.
`myurl.local/node_modules/vue/dist/vue.js`

This is fixed when I pass in deprecated option `vue`:  
```javascript
beforeEach(mountVue(MyComponent, {
  vue: 'otherpathtovue.com/vue.js',
}))
```

**Comment by amirrustam** [comment]
Hi @patrikniebur. The 404 is a little strange since Vue is no longer included via a `script` tag. When the [example tests](https://travis-ci.org/bahmutov/cypress-vue-unit-test/builds/335643907) run serially this issue doesn't occur.

Can you provide any code so I can reproduce this?

**Comment by patrikniebur** [comment]
Sure, this is the simplest example

```javascript
import Vue from 'vue';
import mountVue from 'cypress-vue-unit-test';

const MyComponent = new Vue({
	name: 'MyComponent',
	template: `<h1>My Component</h1>`,
});

describe('Visit page', () => {
	it('Go to url', () => {
		cy.visit('http://www.google.com/');
	});
});

describe('This should mount Vue component', () => {
	before(mountVue(MyComponent));
	it('Should not fail', () => {});
});

```

In this test it tries to load vue from  `https://www.google.com/node_modules/vue/dist/vue.js` 
Today I've updated to `1.10.0` but it's still the same issue.
