### ISSUE TITLE
document.body refers to the spec iframe instead of the app iframe

### ISSUE THREAD

**Issue by smclt30p** [bahmutov/cypress-vue-unit-test#122]
- 1.11.1
- Linux

For example, if you use [Clockpicker](https://weareoutman.github.io/clockpicker/) within a Vue SFC, the clockpicker attaches to the Spec iframe instead of the App iframe because document.body points to the spec iframe, and not the app iframe. This is caused by the following statement:

$(document.body).append(popup);

Thus, Cypress tests fail that are querying anything that is dynamically added to the body. document.body does not point to the app iframe, but the spec iframe.

**Comment by JessicaSachs** [comment]
Gonna close this. Please let me know if this is still an issue
