### ISSUE TITLE
[Bug] Requires a peer of cypress@^2.0.0 when installed Cypress 3.1.0 already

### ISSUE THREAD

**Issue by electrocnic** [bahmutov/cypress-vue-unit-test#143]
- version
  - Cypress: 3.1.0
  - cypress-vue-unit-test: 1.11.0
  - npm: 6.1.0
  - vue: 2.5.17

- platform
  - Windows 10 Home
- expected behavior
This tool (cypress-vue-unit-test) should accept `cypress@3.1.0` as peer (and all newer versions).
- actual behavior
`npm WARN cypress-vue-unit-test@1.11.0 requires a peer of cypress@^2.0.0 but none is installed. You must install peer dependencies yourself.`
At least Cypress cannot run my tests where I use cypress-vue-unit-test, telling me that some dependencies might be missing or so. I cannot tell whether the npm warning is the cause of the testing-issue, but it would be nice to see that warning message going away.

**Comment by josephting** [comment]
`cypress@^2.0.0` will only match up until `cypress@2.1.0`.
Therefore, with `3.1.0` installed, that warning showing up is not really a bug.

However, it'll be nice if we can get a new npm release. @bahmutov

**Comment by josephting** [comment]
@electrocnic This is fixed with [v1.11.2](https://github.com/bahmutov/cypress-vue-unit-test/releases/tag/v1.11.2).

**Comment by bahmutov** [comment]
closed as fixed
