### ISSUE TITLE
[help] Using cy.clock

### ISSUE THREAD

**Issue by mornir** [bahmutov/cypress-vue-unit-test#146]
Hi!
First I'd like to thank you for this library. I already use Cypress for my E2E tests and it's great to be able to use the same tool for unit tests.

I tried to convert a tutorial from Laracasts using vue-test-utils + mocha, with cypress-vue-unit-test. But I have trouble faking time.

Here is what I want to achieve:
https://github.com/laracasts/testingvue/blob/master/episode-10/test/Countdown.spec.js
video: https://laracasts.com/series/testing-vue/episodes/9

My current not working solution:

```js
import mountVue from 'cypress-vue-unit-test'
import Countdown from '../../../../src/components/Countdown'
import { addSeconds } from 'date-fns'

describe('Countdown', () => {
  let clock
  beforeEach(() => {
    clock = Cypress.sinon.useFakeTimers()
    mountVue(Countdown, {
      propsData: {
        until: addSeconds(clock.Date(), 10),
      },
    })()
  })
  afterEach(() => {
    clock.restore()
  })
  it('renders a countdown timer', () => {
    cy.contains('10 seconds')
  })
})
```
IMO the problem is that Cypress is not setting `new Date()` to 1 January 1970 in the actual component.

It would be nice to have a working example in the readme about testing timers.

Cheers

**Comment by mornir** [comment]
I tested [this component](https://github.com/mornir/tdd-vue-laracast/blob/master/src/components/Countdown.vue) without mounting it and everything works fine.
**✔ This test passes:**
```js
describe('Countdown', () => {
  it('renders a countdown timer', () => {
    cy.clock()
    cy.visit('/')
    cy.contains('10 Seconds')
    cy.tick(1000)
    cy.contains('9 Seconds')
  })
})
```
But the unit test fails because cy.clock doesn't override the native global functions related to time.
**❌ This test fails:** 
```js
describe('Countdown', () => {
  beforeEach(
    mountVue(Countdown, {
      propsData: {
        until: moment().add(10, 'seconds'),
      },
    })
  )

  it('renders a countdown timer', () => {
    cy.clock()
    cy.contains('10 Seconds')
    cy.tick(1000)
    cy.contains('9 Seconds')
  })
})
```
@bahmutov @amirrustam Sorry to bother you 🙇‍♂️, but could you just confirm that this divergent behavior of cy.clock is normal?
(And, on an unrelated note, I've opened two pull requests to improve the readme 😊)

**Comment by amirrustam** [comment]
Thanks for the PRs. Always appreciated. I merged them in.

I'll find some time this week to reproduce this on my end this week. Are you running latest version of Cypress? We had some fixes for `cy.clock` in version `3.1.3`.

**Comment by mornir** [comment]
Thanks for merging.

Yes, I am running Cypress version 3.1.3. 
My goal was to redo all the tests from [this tutorial](https://laracasts.com/series/testing-vue), but using cypress-vue-unit-test instead of mocha/vue-test-utils. I succeeded for all components, except for the [counter one](https://laracasts.com/series/testing-vue/episodes/9).

Using Cypress as a test runner make unit testing really easy and fun ✌

**Comment by amirrustam** [comment]
Glad to hear you're having fun. 🙂
I'll try to reproduce, and will follow up.

**Comment by akosipax** [comment]
@amirrustam @bahmutov I'm also having this issue. Here's the code to reproduce it: https://github.com/akosipax/cy-vue-unit-test-146

Thanks so much for this wonderful plugin!

**Comment by DavidGWheeler** [comment]
somewhat similar I think?

my goal is to override the local clock with cy.clock() then I want to click a button, setting a timestamp value in localStorage.  I then want to tick forward one calendar month.  Upon reloading the page I expect a notification which was previously dismissed re-appear.

cy.clock(Date.now());
cy.get(CIP.selectors.claimsSearchNotice)
                .should('be.visible')
                // dismiss it
                .within(() =>
                    cy.get('i')
                        .should('contain.class', 'icon-close')
                        .click()
                )
                .get(CIP.selectors.claimsSearchNotice)
                .should('not.be.visible');
            // shade returns once 30 days pass
            cy.clock(Date.now()).debug()  
                // this matches the timestamp placed on the localStorage item (expected)
                .then(clock => clock.tick(2.765e+9)).debug() // this matches that same timestamp + ~one month (expected)
                .reload();
            cy.clock().debug();  
            // Command Name:     clock cypress_runner.js:85238 Command Args: []length: 0__proto__: Array(0) (What the eff??)
             .visit('/claims');
            cy.get(CIP.selectors.claimsSearchNotice)
                .should('be.visible'); (FAIL!!!)

**Comment by mornir** [comment]
The solution is to initialize the date within the then() call to ensure that Cypress overrides the native Date object:
```js
   cy.clock().then(() => {
      var date = new Date()
      date.setSeconds(date.getSeconds() + 10)
      mount(Countdown, {
        propsData: { until: date },
      })
    })
```
https://github.com/mornir/cypress-laracast-vue-testing/blob/master/tests/components/countdown.spec.js#L8

Also: don't use Cypress.moment because it seems that `cy.clock` doesn't override its methods.
