### ISSUE TITLE
How to pass props when mounting a component ?

### ISSUE THREAD

**Issue by leRenart** [bahmutov/cypress-vue-unit-test#29]
Is my understanding that we cannot mount a SFC and pass props as in vue-test-utils.

```
const wrapper = shallow(Component);
wrapper.setProps({ foo: 'bar' });
```

What could be an alternative ? use a shallow parent and pass data works indeed, just want to know if this is the right (and only) approach.

```

import mountVue from 'cypress-vue-unit-test';
import Test from '@/Test';

const template = `
<Test
  :prop_1="prop_1"
  :prop_2="prop_2">
</Test>
`;

const components = {
  Test,
};

const data = {
  prop_1: 'prop #1',
  prop_2: 'prop #2',
};

/* eslint-env mocha */
describe('Test', () => {
  beforeEach(mountVue({ template, data, components }));

  it('test prop #1', () => {
    cy.get('span:nth-of-type(1)').should('contain', 'prop #1');
  });

  it('test prop #2', () => {
    cy.get('span:nth-of-type(2)').should('contain', 'prop #2');
  });
});
```

**Comment by amirrustam** [comment]
You're correct there is no way to programmatically set props when mounting, and yes currently you set your props within your template. If you don't want to redefine a new template every time you'd like to test a component with different props, you could have a template function that accepts your props and does string interpolation to generate the desired template and props combo.

I've thought about this as well, and I actually have a `setProps` prototype. I did it a little while ago, and I can look further into it if @bahmutov thinks it's a worthwhile direction for the project.

**Comment by bahmutov** [comment]
yeah @leRenart this is the way to do this - you need to pass them separately, because that's how a "normal" app would do this. But you can easily write a small wrapper function to make it more convenient. After all, Cypress is just JavaScript. If you write something convenient, you can make it as a pull request to this lib to help others

**Comment by slieker-d** [comment]
This was a "missing" feature for our team. Hope to see this in a future release.
