### ISSUE TITLE
Missing build step to output library as dist

### ISSUE THREAD

**Issue by JessicaSachs** [bahmutov/cypress-vue-unit-test#295]
Currently, `cypress-vue-unit-test` doesn't build a dist directory.

When users require `cypress-vue-unit-test` they're requiring the library's source and thus have to be able to transpile all of the code properly. This is an issue if `cypress-vue-unit-test` uses functionality with a webpack configuration that isn't able to compile it.

`cypress-react-unit-test` has a build step that outputs to `dist`. `cypress-vue-unit-test` needs one, too

**Comment by bahmutov** [comment]
Let my people build ⚒
