### ISSUE TITLE
Error: runtime-only build of Vue (w/ experimental component support)

### ISSUE THREAD

**Issue by probil** [bahmutov/cypress-vue-unit-test#305]
I'm trying to use experimental component testing and I've got a strange error (in browser/electron console) while using the library:
```
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.
```

Here is my test:
```js
import { mountCallback } from 'cypress-vue-unit-test';
import Moveable from '../../src/components/Moveable.vue';

const style = `
  .moveable {
    position: relative;
    width: 300px;
    height: 200px;
    text-align: center;
    font-size: 40px;
    margin: 0 auto;
  }`;

const template = `
  <Moveable class="moveable">
    <span>Content</span>
  </Moveable>
`;

describe('Moveable', () => {
  beforeEach(mountCallback({
    template,
    components: {
      Moveable,
    },
  }, { style }));
  it('Works', () => {
    cy.get('Content').should('exist');
  });
});
```

This is strange because automatically generated component test `HelloWorld.spec.js` works fine. 🤔 
Moreover, I didn't get the error when I use `mount` function on that component directly:
```js
  it('Works', () => {
    mount(Moveable);
    cy.get('Content').should('exist');
  });
```
But this is not suitable for my case as I need extra styles and configuration for the wrapper element.

Moveable itself has no other vue component imported. Content of Moveable.vue is here https://github.com/probil/vue-moveable/blob/master/src/components/Moveable.vue

I would be glad to provide any additional details.

--- 

| Lib | Version
| --- | --- |
| Vue CLI | 4.3.1 |
| Cypress| 4.5.0 |
| cypress-vue-unit-test|  2.0.0 |
| Vue & vue-template-compiler | 2.6.11 |

**Comment by JessicaSachs** [comment]
Your webpack config is serving the runtime build, not [runtime + compiler](https://vuejs.org/v2/guide/installation.html#Explanation-of-Different-Builds). If it was working correctly, your webpack config would be mapping `import 'vue'` to `import 'vue/dist/esm.js'`.

Unsure why that's not happening.

You could help me out by:
1. Sharing your Cypress `plugin.js` file
2. (better) Sharing a reproduction repo

BTW, did you use `vue add cypress-experimental` to add component testing to your project? It should've scaffolded a proper `plugin.js` file using `onFileDefaultPreprocessor` which should work with the latest Vue CLI.
---

A longer answer about templates vs importing components is below:

There are two builds in Vue: one that includes the template compiler and one that is "runtime-only". See the [docs explanation](https://vuejs.org/v2/guide/installation.html#Explanation-of-Different-Builds)

When you import a Vue component in your spec like `import MyComponent from 'MyComponent.vue'`, the Vue SFC compiler compiles the template, script, and styles at build time.

When you use a template string, you require the browser to do that same compilation at runtime.

In production apps, it is performant to only ship the runtime and to have all Vue component compilation happen at build time.

However, for the purposes of testing, templates are pretty convenient. To support `templates`, we want to ship the runtime + compiler, so we override webpack alias/resolve to map `import Vue from 'vue'` => `import Vue from 'vue/dist/vue.esm.js'`

That's done in [this function](https://github.com/bahmutov/cypress-vue-unit-test/blob/master/preprocessor/webpack.js#L46-L51). If you're not using `onFileDefaultPreprocessor`, then you'd have an issue compiling templates.

---

Anyway, send me what you have for plugin.js or a reproduction repository.

Thank you for reporting an issue! 🐛

**Comment by probil** [comment]
Hey, @JessicaSachs :wave
Thanks for your answer

1. Yes, I've used `vue add cypress-experimental`
2. I haven't changed `plugin.js` generated by that util
3. Here is a repo with a branch, which can be used to reproduce the issue
https://github.com/probil/vue-moveable/tree/test-new-e2e
The problem is in `Moveable.spec.js`

**Comment by JessicaSachs** [comment]
Thank you *so* much. I think it's because you were shipping a library. I'm forking your repo and will try to incorporate it into an e2e suite for the plugin. Releasing the fix now.

**Comment by JessicaSachs** [comment]
OK, just did a `npm install` and the error is fixed. Your spec's selector is incorrect. You'll need to update it to something like:

```js
// Old, `Content` isn't a valid DOM selector
// cy.get('Content').should('exist');

// Works, uses the target's class to select it, then asserts on the text
cy.get('.moveable').should('contain.text', 'Content');
```

**Comment by probil** [comment]
🎉 
Thanks, @JessicaSachs 
Have a great day!
