### ISSUE TITLE
Components are not properly destroyed (w/ experimental component support)

### ISSUE THREAD

**Issue by probil** [bahmutov/cypress-vue-unit-test#309]
Hi there 👋 

I'm trying to use experimental component testing and I've got an issue. 

My component adds an element directly to the DOM using `document.body.appendChild()`.  The action is performed in `mounted()` hook and then `beforeDestroy()` is used to remove it.

The problem is that neither `beforeDestroy()` nor `destroyed()` is called in between tests so my elements accumulate in body. I can't reliably verify whether added element exist or not because of it.

Here is a simple example (based on default `HelloWorld.vue`):
```vue
<template>
    <h1 data-testid="hello-world-title">
        Hello world! This is your first component tested by Cypress
    </h1>
</template>
<script>
export default {
  mounted() {
    const elem = document.createElement('div');
    const randomTop = Math.round(Math.random() * 500);
    const randomLeft = Math.round(Math.random() * 500);
    elem.style.cssText = `position:absolute;top:${randomTop}px;left:${randomLeft}px;width:100px;height:100px;background:#000`;
    document.body.appendChild(elem);
    this.$artifact = elem;
  },
  beforeDestroy() {
    console.log('Destroyed');
    document.body.removeChild(this.$artifact);
  },
};
</script>
```
Here is the test file:
```js
import { mount } from 'cypress-vue-unit-test';
import HelloWorld from '../../src/components/HelloWorld.vue';

describe('HelloWorld', () => {
  it('Works awesomely', () => {
    mount(HelloWorld);
    cy.get('[data-testid=hello-world-title]').should('exist');
  });
  it('Works awesomely', () => {
    mount(HelloWorld);
    cy.get('[data-testid=hello-world-title]').should('exist');
  });
  it('Works awesomely', () => {
    mount(HelloWorld);
    cy.get('[data-testid=hello-world-title]').should('exist');
  });
  it('Works awesomely', () => {
    mount(HelloWorld);
    cy.get('[data-testid=hello-world-title]').should('exist');
  });
});
```
Screenshot:
<img width="739" alt="Screenshot 2020-05-10 at 00 10 03" src="https://user-images.githubusercontent.com/6773202/81485041-0c07cc80-9253-11ea-8633-621d72726922.png">

**Actual result**: `beforeDestroy()` hook not is called and elements accumulate
**Expected result**: `beforeDestroy()` hook is called and elements are deleted

---

| Lib | Version
| --- | --- |
| Vue CLI | 4.3.1 |
| Cypress| 4.5.0 |
| cypress-vue-unit-test|  2.0.1 |
| Vue & vue-template-compiler | 2.6.11 |

**Comment by probil** [comment]
Just discovered that calling `Cypress.vue.$destroy()` after the last command helps. 
But the approach itself is hacky. Maybe it can help to deal with the issue.

```js
describe('HelloWorld', () => {
  it('Works awesomely', () => {
    mount(HelloWorld);
    cy.get('[data-testid=hello-world-title]').should('exist').then(() => {
      Cypress.vue.$destroy();
    });
  });
  it('Works awesomely', () => {
    mount(HelloWorld);
    cy.get('[data-testid=hello-world-title]').should('exist').then(() => {
      Cypress.vue.$destroy();
    });
  });
  it('Works awesomely', () => {
    mount(HelloWorld);
    cy.get('[data-testid=hello-world-title]').should('exist').then(() => {
      Cypress.vue.$destroy();
    });
  });
  it('Works awesomely', () => {
    mount(HelloWorld);
    cy.get('[data-testid=hello-world-title]').should('exist').then(() => {
      Cypress.vue.$destroy();
    });
  });
});
```

**Comment by JessicaSachs** [comment]
Hey @probil,

Your support file should be tearing down the DOM inside of the mounting container `#cypress-jsdom`. We don’t call destroy automatically right now. I’m hesitant to add it because you can call mount multiple times in one test, so you might have multiple dom leaks in one test.

Mounting outside of the app or root and using document createElement inside the component to create modals etc is less common so if you’re testing components with modals, you’ll need to manually call $destroy on the component or cleanup the DOM manually.

My understanding is that when writing tests in other frameworks this isn’t usually handled automatically.

In Vue Test Utils I think you’d have to manually clean it up, too.

In cypress e2e we rely on cy.visit as a method to blow away previous pages. 

Perhaps we would remove the ability to do multiple mounts in one test. What do you think?

**Comment by probil** [comment]
It's ok if I have destroy component manually. The main inconvenience is that I need to use `.then()` after the last command.

Instead of :
```js
it('Works awesomely', () => {
    mount(HelloWorld);
    cy.get('[data-testid=hello-world-title]').should('exist').then(() => {
      Cypress.vue.$destroy();
    });
  });
```
It would be nice to have something like that:
```js
it('Works awesomely', () => {
    mount(HelloWorld);
    cy.get('[data-testid=hello-world-title]').should('exist');
    destroy();
  });
```

**Comment by probil** [comment]
Destroying mounted component after each test did the trick
```js
 afterEach(() => {
    Cypress.vue.$destroy();
  });
```

**Comment by JessicaSachs** [comment]
Super! In the future the component instance will not be on the global window, it will be a return value from `mount`.

You could have multiple mounts per spec. It would be uncommon but programmatically possible. Let's open a new issue about the `<style>` duplication -- this is part of an Epic related to cleaning up browser state and we will tackle it next.

**Comment by probil** [comment]
Thanks for the response @JessicaSachs 
I'll create a new issue for styles in a minute.

---

UPDATE: Oh. I see you have already done that ;)
