### ISSUE TITLE
Docs for Custom Webpack + Vue Setup

### ISSUE THREAD

**Issue by ecofriend** [bahmutov/cypress-vue-unit-test#310]
Thank you for taking time to open a new issue. Please answer a few questions to help us fix it faster. You can delete text that is irrelevant to the issue.

## Is this a bug report or a feature request?

bug (broken link in README.md)

"Manual webpack configuration is possible and documented here." 
The "here" link is broken. (Could it be "https://github.com/cypress-io/cypress-webpack-preprocessor"?)

Background: I'm building an app using Meteor, which doesn't use webpack so I need documentation on how to set up my project to use Cypress testing.

**Comment by JessicaSachs** [comment]
I just caught that too when I was auditing the README. Your finished app is a [great example](https://github.com/ecofriend/MeteorTestingWithCypress/blob/master/tests/cypress/plugins/index.js). You manually setup the appropriate loaders, etc.

A fix for this would be to add a section on "Customizing your Webpack Configuration" and send people to the appropriate [vue-loader](https://vue-loader.vuejs.org/guide/#manual-setup) and [webpack preprocessor](https://github.com/cypress-io/cypress-webpack-preprocessor#modifying-default-options) links.

I'm happy to take a PR if you'd like to do it.

**Comment by ecofriend** [comment]
Hi Jessica, looks like the doc has been updated already to include info about vue-loader and webpack preprocessor.

**Comment by JessicaSachs** [comment]
🙃Yes, you're right.
