### ISSUE TITLE
Node Sass does not yet support your current environment

### ISSUE THREAD

**Issue by zack-pronto** [bahmutov/cypress-vue-unit-test#319]
Thank you for taking time to open a new issue. Please answer a few questions to help us fix it faster. You can delete text that is irrelevant to the issue.

###  Is this a bug report or a feature request? `Bug Report`

If this is a bug report, please provide as much info as possible

- version: `"cypress-vue-unit-test": "^2.0.1",`
- platform: `macOS 10.15.4`
- expected behavior
  - Node-sass should be able to run
- actual behavior
 ```
Error: Webpack Compilation Error
./resources/js/components/IntegrationManagement/IntegrationManagement.vue?vue&type=style&index=0&id=573631a4&lang=scss&scoped=true& (./node_modules/css-loader/dist/cjs.js!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/components/IntegrationManagement/IntegrationManagement.vue?vue&type=style&index=0&id=573631a4&lang=scss&scoped=true&)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (76)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
```

### Explanation

I've been trying to get cypress-vue-unit-test running for a while now and I've encountered a number of issues that I think are specific to our app setup, but this current issue I can't seem to get through. I am getting an error that Node-sass isn't compatible for my current environment. All of the solutions online say to run `npm rebuild node-sass` but that doesn't seem to have worked for me. I've tried using older versions of node (v9, v10, v12, v14) to run `cypress open` but it still fails every time with the same error. All of these node versions are currently supported by `node-sass@4.14.1`, according to [their docs](https://github.com/sass/node-sass/releases/tag/v4.14.1).

Here's my [webpack config for `cypress/plugins/index.js`](https://gist.github.com/zack-pronto/4fcddc79adccb9e025907a4a2ccef34f). 

Here's what I see in the test runner:

![CleanShot 2020-06-09 at 14 13 40](https://user-images.githubusercontent.com/63250712/84196369-543a2a80-aa5d-11ea-8997-e40f9ef89447.png)

### Help?

Any help would be greatly appreciated. Is there a specific version of node that I need to use? Is there a loader that I need to add to the webpack config? Any tips would be a huge help. Thanks in advance!

**Comment by bahmutov** [comment]
Hi @zack-pronto - can you try using `nodeVersion: system` in your `cypress.json` file? https://on.cypress.io/configuration#Node-version This will tell Cypress not to use the bundled Node version, but whatever is installed on your system, which should match the Node version used to install Sass native extensions

**Comment by zack-pronto** [comment]
Wahoo! That solved it! Thank you for the quick response! 👏

**Comment by bahmutov** [comment]
Hey we appreciate you trying it out and powering through the problems. If you have any more feedback let us know

**Comment by zack-pronto** [comment]
Will do. Thanks again. Really appreciate it.
