### ISSUE TITLE
Feature Request: Co-locating Spec Files with Component Files

### ISSUE THREAD

**Issue by zack-pronto** [bahmutov/cypress-vue-unit-test#320]
## Feature Request: Co-locating Spec Files

With integration tests, it makes sense to move those into a separate folder (ie `cypress/integration`). But with unit tests, I have really appreciated being able to co-locate the spec files next to the components they are testing when using other tools like Jest. Is that possible with `cypress-vue-unit-test`? 

I have this setup in `cypress.json`:

```
{
	"experimentalComponentTesting": true,
	"componentFolder": "resources/js",
	"nodeVersion": "system",
	"fileServerFolder": "public"
}
```

Currently, when I run my test suite, it attempts to run every file in my `resources/js` folder, even component files like `MyComponent.vue`, which obviously fails because there are no test or assertions in that file. 

I would prefer if I could just tell Cypress what parent folder to look in and then it would only attempt to run tests in files that follow a specific naming convention, like `.spec.js` or `.test.js` or whatever. Is that currently possible?

Thanks in advance

**Comment by mornir** [comment]
Hi!
I think this is already possible with the `testFiles` option:
```json
{
  "testFiles": "**/*.spec.js*",
  "experimentalComponentTesting": true,
  "componentFolder": "resources/js"
}
```

**Comment by zack-pronto** [comment]
Awesome. Thanks for your help @mornir. Much appreciated. 

For anyone else coming along later, the docs for that are here: https://docs.cypress.io/guides/references/configuration.html#Folders-Files
