### ISSUE TITLE
Oops...we found an error preparing this test file

### ISSUE THREAD

**Issue by b805rohit** [bahmutov/cypress-vue-unit-test#335]
Oops...we found an error preparing this test file:
tests\components\HelloWorld.spec.js
This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

A missing file or dependency
A syntax error in the file or one of its dependencies
Fix the error in your code and re-run your tests.

**Comment by bahmutov** [comment]
While this issue is missing any details, can you check your cypress/plugins/index.js file? Or maybe if this is a Vue CLI app `tests/plugins/index.js` file. It should be

```js
// default webpack file preprocessor is good for simple cases
// Required to temporarily patch async components, chunking, and inline image loading
const {
  onFileDefaultPreprocessor
} = require("cypress-vue-unit-test/dist/preprocessor/webpack");

module.exports = (on, config) => {
  on("file:preprocessor", onFileDefaultPreprocessor(config));
  return config
};
```

Like shown in https://github.com/bahmutov/vue-component-test-example

**Comment by bahmutov** [comment]
Try again or look at the above link for an example
