### ISSUE TITLE
Show how to pass slots to the component while mounting it

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/cypress-vue-unit-test#364]
Help wanted - I don't know how to set up slots and scoped slots via Vue constructor

https://vuejs.org/v2/guide/components-slots.html

## To work on this

clone the repo
install dependencies
in one terminal start watch with `npm run build:watch`
in another terminal open Cypress with `npx cypress open`
modify `src/index.ts` file while working with test https://github.com/bahmutov/cypress-vue-unit-test/blob/bf0ace338c3bec42dd93a9d35ca4511b9e1523f6/cypress/component/basic/small-examples/AppInput.spec.js#L23

**Comment by JessicaSachs** [comment]
Here you go https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth

What you really want is something like this https://jsfiddle.net/Lzeja2rd/110/

**Comment by bahmutov** [comment]
But how does this translate into the way the component is created right now? Why does Vue have so many different syntaxes 

https://github.com/bahmutov/cypress-vue-unit-test/blob/bf0ace338c3bec42dd93a9d35ca4511b9e1523f6/src/index.ts#L435-L445

**Comment by bahmutov** [comment]
Ok, I will leave it to someone who knows what they are doing, the test assertion to check if the slot is handled correctly is in https://github.com/bahmutov/cypress-vue-unit-test/blob/bf0ace338c3bec42dd93a9d35ca4511b9e1523f6/cypress/component/basic/small-examples/AppInput.spec.js#L23 and it would be nicer to add more tests around them, similar to https://github.com/testing-library/vue-testing-library/blob/master/src/__tests__/slots.js

**Comment by JessicaSachs** [comment]
I show this in my fiddle -- slots don't make sense unless you pass in what you're trying to inject. The current syntax should create a "wrapper" root Vue node (like what I do in my [fiddle](https://github.com/bahmutov/cypress-vue-unit-test/issues/364#issuecomment-660366290)) and then you should render the Component Under Test as the first child of this Root Vue Node.

**Comment by bahmutov** [comment]
That’s kind of big change, no

**Comment by JessicaSachs** [comment]
The initial change wasn't a big deal, but I uncovered a lot of bugs with the API and fixed a lot of "hidden" errors we were throwing in the console. Vue Test Utils doesn't let you suppress problematic errors and it bubbles them so you don't accidentally pass a component that won't work in production.
