### ISSUE TITLE
Component bundling without access to webpack.config file

### ISSUE THREAD

**Issue by diegopamio** [bahmutov/cypress-vue-unit-test#41]
## Is this a bug report or a feature request?
Feature Request

If this is a new feature request, please describe it below

For those projects were we don't have direct access to the webpack.config file, like quasar 0.15+, how can we bundle the Vue single file components?

**Comment by amirrustam** [comment]
You can use a separate webpack config file along with the Cypress [Preprocessor API](https://docs.cypress.io/api/plugins/preprocessors-api.html). We have examples just for this right here: https://github.com/cypress-io/cypress-webpack-preprocessor. You can also check out the included preprocessor example: https://github.com/bahmutov/cypress-vue-unit-test/blob/master/preprocessor/webpack.js

While you don't have direct access to Quasar's webpack config, you can find it here: https://github.com/quasarframework/quasar/blob/dev/build/webpack.config.js
And I would put that in a build/webpack.cypress.js. That's what I've done in the past with Vuetify, which is similar to Quasar. 

Hope that helps.
