### ISSUE TITLE
Extend Vue before mounting test Component

### ISSUE THREAD

**Issue by apathetic** [bahmutov/cypress-vue-unit-test#5]
Rather than mounting the test Component in a vanilla Vue instance, it would be nice to have the ability to extend Vue first. 

For example, in my app I have global mixins that all my Components require, as well as a few global functional Components that are also used throughout. It would be nice to have an affordance to add them into the Vue environment before the test Component is mounted, ie: 

```
  cy
    .window()
    .its('Vue')
    .then(Vue => {

      Vue.mixin({ 
        // any global Vue mixins used
      }):
      Vue.component({  
        // any global Vue components used in the App
      }):
      // etc...

      Cypress.vue = new Vue(component).$mount('#app')
    })
}
```

**Comment by bahmutov** [comment]
Sure, that is easy to do. Maybe pass them as options to the mount call? But because there is also `Vue.use` it would be nice to have some flexiblity

```js
const extensions = {
  use: // global Vue 
  mixin: // global Vue mixins
  component: // global Vue component
}
mountVue(myCode, { vue: 'https...', extensions })
```

**Comment by bahmutov** [comment]
Version `1.6.0` has been published to NPM. The full release note can be found at [cypress-vue-unit-test/releases/tag/v1.6.0](https://github.com/bahmutov/cypress-vue-unit-test/releases/tag/v1.6.0).

**Tip:** safely upgrade dependency cypress-vue-unit-test in your project using [next-update](https://github.com/bahmutov/next-update)

**Comment by apathetic** [comment]
NIce !
