### ISSUE TITLE
Can I use Vue DevTools within the Cypress managed Chrome?

### ISSUE THREAD

**Issue by alukos** [bahmutov/cypress-vue-unit-test#63]
Advise, please, workflow development set of vue-components through BDD. I would like to have access to both Cypress and Vue Devtools

**Comment by amirrustam** [comment]
I'm not completely clear on your question. Are you asking if you can use Vue DevTools within the Cypress managed Chrome?

**Comment by alukos** [comment]
Sorry, poorly formulated. Yes, I meant the ability to use Vue DevTools within the Cypress managed Chrome

**Comment by amirrustam** [comment]
Currently Vue DevTools does not support Vue instances with iframes, so this is not possible. However, supporting iframes is an open issue: https://github.com/vuejs/vue-devtools/issues/353
