### ISSUE TITLE
Vue CLI Plugin

### ISSUE THREAD

**Issue by DrSensor** [bahmutov/cypress-vue-unit-test#77]
Hello, 
Is there any plan to write [vue-cli-plugin]( https://github.com/vuejs/vue-cli/blob/dev/docs/plugin-dev.md) so this library can be added easily?

> https://github.com/vuejs/vue-cli/issues/1026

Thankyou

**Comment by mornir** [comment]
https://github.com/jessicasachs/vue-cli-plugin-cypress-experimental
@amirrustam  This issue can be closed 😃 
@JessicaSachs Thanks for the plugin!
