### ISSUE TITLE
Rework the README

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/cypress-vue-unit-test#8]
The readme grew to be too long. Need to restructure it

- maybe add table of contents? Keep everything inside single README but provide quick links from the top
- move examples into separate files, keeping only top level links in the README

**Comment by amirrustam** [comment]
I think in its current state the first option of just adding a table of contents is best. Viewing the usage examples back-to-back helps create quick mental model of what is possible without having to switch between pages. If the docs get any bigger then the second option will probably be better.

**Comment by bahmutov** [comment]
Yeah, I am thinking just adding table of contents in the beginning would solve all problems. I love single README too, just text search finds everything quickly.

**Comment by amirrustam** [comment]
@bahmutov Just did it. 🙂
